server:
  port: 8081
  
eureka:
  client:
    service-url:
      defaultZone: http://118.24.49.184:8761/eureka/,http://118.24.49.184:8762/eureka/,http://118.24.49.184:8763/eureka/
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
spring:
  application:
    name: local_client